services:
  fastapi:
    #image: dejanualex/fastapi:0.0.3
    build:
      context: .
      dockerfile: Dockerfile
    container_name: localfastapi
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
    
  grafana:
    image: grafana/grafana-oss:latest
    container_name: localgrafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana_volume/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana_volume/datasources.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
    depends_on:
      - prometheus
    links:
      - prometheus
    restart: always

  prometheus:
    image: prom/prometheus:latest
    hostname: prometheus
    container_name: localprometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus_volume/prometheus.yaml:/etc/prometheus/prometheus.yaml
    command:
      - '--web.enable-lifecycle'
      - '--config.file=/etc/prometheus/prometheus.yml'