#!/usr/bin/env bash

# usage ./test_endpoint.sh APIKEY
curl -X POST http://localhost:8000/receive \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $1" \
  -d '{
  "receiver": "localtest",
  "status": "firing",
  "alerts": [
    {
      "status": "firing",
      "labels": {
        "alertname": "fails",
        "grafana_folder": "alertfolder",
        "instance": "webapp:8081",
        "job": "webapp_metrics"
      },
      "annotations": {
        "summary": "FAAAIL"
      },
      "startsAt": "2025-08-07T13:04:50Z",
      "endsAt": "0001-01-01T00:00:00Z",
      "generatorURL": "http://localhost:3000/alerting/grafana/feuad4f31kk5cc/view?orgId=1",
      "fingerprint": "5f2060ba352eef89",
      "silenceURL": "http://localhost:3000/alerting/silence/new?alertmanager=grafana&matcher=__alert_rule_uid__%3Dfeuad4f31kk5cc&matcher=instance%3Dwebapp%3A8081&matcher=job%3Dwebapp_metrics&orgId=1",
      "dashboardURL": "",
      "panelURL": "",
      "values": {
        "A": 46,
        "C": 1
      },
      "valueString": "[ var='A' labels={__name__=my_failures_total, instance=webapp:8081, job=webapp_metrics} value=46 ], [ var='C' labels={__name__=my_failures_total, instance=webapp:8081, job=webapp_metrics} value=1 ]",
      "orgId": 1
    }
  ],
  "groupLabels": {
    "alertname": "fails",
    "grafana_folder": "alertfolder"
  },
  "commonLabels": {
    "alertname": "fails",
    "grafana_folder": "alertfolder",
    "instance": "webapp:8081",
    "job": "webapp_metrics"
  },
  "commonAnnotations": {
    "summary": "FAAAIL"
  },
  "externalURL": "http://localhost:3000/",
  "version": "1",
  "groupKey": "{}/{__grafana_autogenerated__=\"true\"}/{__grafana_receiver__=\"localtest\"}:{alertname=\"fails\", grafana_folder=\"alertfolder\"}",
  "truncatedAlerts": 0,
  "orgId": 1,
  "title": "[FIRING:1] fails alertfolder (webapp:8081 webapp_metrics)",
  "state": "alerting",
  "message": "**Firing**\n\nValue: A=46, C=1\nLabels:\n - alertname = fails\n - grafana_folder = alertfolder\n - instance = webapp:8081\n - job = webapp_metrics\nAnnotations:\n - summary = FAAAIL\nSource: http://localhost:3000/alerting/grafana/feuad4f31kk5cc/view?orgId=1\nSilence: http://localhost:3000/alerting/silence/new?alertmanager=grafana&matcher=__alert_rule_uid__%3Dfeuad4f31kk5cc&matcher=instance%3Dwebapp%3A8081&matcher=job%3Dwebapp_metrics&orgId=1\n"
}'
