apiVersion: v1
kind: Secret
metadata:
  name: {{ include "grafana-hotline.fullname" . }}-secret
  labels:
    {{- include "grafana-hotline.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.twilio.accountSid }}
  TWILIO_ACCOUNT_SID: {{ .Values.twilio.accountSid | b64enc | quote }}
  {{- end }}
  {{- if .Values.twilio.authToken }}
  TWILIO_AUTH_TOKEN: {{ .Values.twilio.authToken | b64enc | quote }}
  {{- end }}
  {{- if .Values.phone.destinationPhoneNumber }}
  DESTINATION_PHONE_NUMBER: {{ printf "+%s" (.Values.phone.destinationPhoneNumber | toString | trimPrefix "+") | b64enc | quote }}
  {{- end }}